### ISSUE TITLE
暖暖功能报错

### ISSUE THREAD

**Issue by KimoeChen** [aaron-lii/TataruBot2#14]
救救孩子QvQ
BOT聊天框出现下文
Error: <class 'aiohttp.client_exceptions.ClientConnectorCertificateError'>

程序内看到的：

06-16 15:14:08 [INFO] nonebot | Event will be handled by Matcher(type='message', module=tatarubot2.plugins.nuannuan)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 980, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 1080, in _create_connection_transport
    await waiter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\asyncio\sslproto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\ssl.py", line 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\塔塔露BOT开发 - 副本\TataruBot2-main\tatarubot2\plugins\nuannuan.py", line 68, in get_qq_doc
    r = await aiohttp_get(url, res_type="text")
  File "C:\Users\Administrator\Desktop\塔塔露BOT开发 - 副本\TataruBot2-main\tatarubot2\plugins\utils.py", line 59, in aiohttp_get
    res = await session.get(url_input)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\client.py", line 536, in _request
    conn = await self._connector.connect(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\aiohttp\connector.py", line 982, in _wrap_create_connection
    raise ClientConnectorCertificateError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host www.youwanc.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')]

**Comment by aaron-lii** [comment]
@KimoeChen  目前的暖暖功能有点垃，只是返回一个腾讯文档链接 https://docs.qq.com/sheet/DY2lCeEpwemZESm5q?tab=dewveu&c=A1A0A0 ，先将就一下把。这几天我看一下能不能换个方式更新一下

**Comment by KimoeChen** [comment]
辛苦大手子

**Comment by aaron-lii** [comment]
@KimoeChen 代码更新了，如果直接下代码跑的话，可以重新下载一下。pip包还没更新，得等后面代码结构改一改再发布。

**Comment by KimoeChen** [comment]
解决了，多谢更新
