### ISSUE TITLE
搜索失败！RuntimeError('Timeout context manager should be used inside a task')

### ISSUE THREAD

**Issue by saki9478** [aaron-lii/TataruBot2#6]
aiohttp请求的时候出现上下文异常
```Traceback (most recent call last):
  File "/root/bot/setubot/YxlBot/.venv/lib/python3.10/site-packages/tatarubot2/plugins/item.py", line 451, in search_item
    return await parse_item_garland(j["Results"][0]["ID"], name_lang)
  File "/root/bot/setubot/YxlBot/.venv/lib/python3.10/site-packages/tatarubot2/plugins/item.py", line 150, in parse_item_garland
    image = await session.get(image_url)
  File "/root/bot/setubot/YxlBot/.venv/lib/python3.10/site-packages/aiohttp/client.py", line 467, in _request
    with timer:
  File "/root/bot/setubot/YxlBot/.venv/lib/python3.10/site-packages/aiohttp/helpers.py", line 701, in __enter__
    raise RuntimeError(
RuntimeError: Timeout context manager should be used inside a task
```
可不可以对`session = aiohttp.ClientSession(timeout=timeout, headers=get_headers())`这个操作进行`async def`封装，或者将模块换成`await httpx.get(url, headers=get_headers())`操作

**Comment by aaron-lii** [comment]
@saki9478 之前用的python3.7没异常，发现是3.10会有问题。现在更新了给aiohttp.ClientSession封装了async，测了下应该正常了。如果有问题我再看看
